server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/cinepass}
    username: ${SPRING_DATASOURCE_USERNAME:cinepass}
    password: ${SPRING_DATASOURCE_PASSWORD:cinepass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

jwt:
  secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
  expiration-ms: ${JWT_EXPIRATION_MS:2700000}
