spring:
  application:
    name: cinepass
  profiles:
    active: dev # default profile

  datasource:
    url: jdbc:postgresql://localhost:5432/cinepass
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWNpbmVwYXNzLXdlYi1hcHBsaWNhdGlvbi1zZWN1cml0eS1hbmQtbXVzdC1iZS1hdC1sZWFzdC0yNTYtYml0cw==}
  expiration-ms: 2700000